//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public string A_id { get; set; }
        public string A_date { get; set; }
        public string A_time { get; set; }
        public string A_name { get; set; }
        public string A_name_detail { get; set; }
        public string A_code { get; set; }
        public string A_link { get; set; }
        public string A_sander { get; set; }
        public string A_assign { get; set; }
        public string A_target { get; set; }
        public string A_status { get; set; }
        public string A_detail { get; set; }
        public string U_status { get; set; }
        public string U_remark { get; set; }
        public string U_date1 { get; set; }
        public string U_detail1 { get; set; }
        public string U_link1 { get; set; }
        public string U_date2 { get; set; }
        public string U_detail2 { get; set; }
        public string U_link2 { get; set; }
        public string U_date3 { get; set; }
        public string U_detail3 { get; set; }
        public string U_link3 { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public string C4 { get; set; }
        public string R1 { get; set; }
        public string R2 { get; set; }
        public string R3 { get; set; }
        public string R4 { get; set; }
        public string A_Brand { get; set; }
        public string Rec1 { get; set; }
        public string Rec2 { get; set; }
        public string Rec3 { get; set; }
    }
}
