//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public string P_id { get; set; }
        public string P_name { get; set; }
        public string P_user { get; set; }
        public string P_pass { get; set; }
        public string P_status { get; set; }
        public string P_using { get; set; }
    }
}
